#!/bin/bash

PROC_NAME="server"
BIN_PATH=`pwd`/install/bin/server

ROOT=${ROOT-../..}

. ${ROOT}/apps/scripts/include/cmdctl.inc

mode=$1
shift || mode="no_action"

case "$mode" in
  'start')
    echo "***** Starting $PROC_NAME server..."
    eval $CMD_PREFIX $BIN_PATH $* &
    ;;
  *)
    cmdctl_server_action $mode $*
    ;;
esac

