#!/bin/bash


ROOT=`readlink -f ../..`

BENCH_TYPE=${BENCH_TYPE:-1}

. ../scripts/include/cmdctl.inc

# Main bench type is 2

if [ $BENCH_TYPE -eq 2 ]; then
    echo "Running benchmarks..."
    TESTS_FILE=$(readlink -f runbench.tests.all)
fi

mapfile -t tests < "${TESTS_FILE}"
for TEST in "${tests[@]}"
do
    TEST_NO_SLASHES=$(echo ${TEST} | sed 's/\//_/g')
    echo "Running test ${TEST} (${TEST_NO_SLASHES})..."
    RUN_EINSTEIN=1 USE_LOG_DIR=1 V=1 LOG_SUB_DIR="${TEST_NO_SLASHES}" ./serverctl restart
    sleep 8
    ./serverctl udscmd pids dbt taintall
    sleep 2
    bash tests/${TEST}
done

exit 0
